workflows:
  build:
    name: "Payflex"
    environment:
      groups:
        - android-signing
        - firebase-config
        - api-keys
    scripts:
      - name: "Configure Android SDK"
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: "Generate APK/AAB"
        script: |
          ./gradlew bundleRelease  # To create the .aab file
          # ./gradlew assembleRelease  # To create the .apk file

    artifacts:
      - "android/app/build/outputs/**/*.aab"
      - "android/app/build/outputs/**/*.apk"

    publishing:
      email:
        recipients:
          - "elderrodrigues49@gmail.com"
        notify:
          success: true
          failure: false
